name: Lint Pull Request

on:
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install  # Change this to the command used to install dependencies (e.g., yarn)

    - name: Run ESLint
      run: npm run lint  # Change this to the linting command for your specific project

